# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/sm8550-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter pdx234,$(TARGET_DEVICE)),)

endif
